apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-preview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-preview
  template:
    metadata:
      labels:
        app: nginx-preview
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80
        
