apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-preview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-preview
  template:
    metadata:
      labels:
        app: nginx-preview
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
