apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: green
  template:
    metadata:
      labels:
        app: nginx
        environment: green
    spec:
      containers:
      - name: nginx
        image: jemesbond/angular:v2
        ports:
        - containerPort: 80
