apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: blue
  template:
    metadata:
      labels:
        app: nginx
        environment: blue
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
